version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-backend
    container_name: laravel-backend
    restart: unless-stopped
    working_dir: /var/www    
    volumes:
      - .:/var/www
      - /var/www/vendor
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - "8000:8000"
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-frontend
    container_name: react-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
